### PR TITLE
Blank screen on iPad issue

### PR DESCRIPTION
**Pull request by jamesporter**
Small thing but will waste a lot of time for a lot of people as soon as they try to enable iPad

### CODE REVIEW

**Review by ryangittings — CHANGES_REQUESTED** [review]
Can you please add an example repo, I haven’t personally come across this issue! :)

**Comment by pedrommcarrasco** [comment]
It's working here 🤔

**Comment by ryangittings** [comment]
Working here too! Must be some specific view issue, sample code would be great to help debug!

**Comment by jamesporter** [comment]
A repo seems over the top as the below reproduces:

```swift
struct ContentView: View {
    var body: some View {
        NavigationView {
            Text("Hello, World!")
        }
    }
}
```
In portrait will get blank screen(!)

I understand why (is master/detail form by default) but for new people this is going to be very confusing.

**Comment by ryangittings** [comment]
What version are you running? I can't recreate that here on 13.2.2 on my iPad. Have you tried a brand new repo?

**Comment by jamesporter** [comment]
Yes. This is really simple actually. By default on iPad it uses master-detail form, which in portrait can easily result in a confusing, completely blank screen. In landscape it will show.

Maybe this is too simple for this repo, will close.

**Pull request closed without merging**
